version: '3.8'

services:

  nestjs-app:
    image: lib-app:latest
    container_name: nestjs-container
    ports:
      - "3000:3000"  # Map port 8000 on the host to port 3000 in the container
    environment:
      APP_ENV: development
      APP_PORT: 3000
    env_file:
      - .env  # Use environment variables from the .env file

    networks:
      - default

networks:
  default:
    external:
      name: database_default